---
name: device1  # This name is pre-pended to each log message
channel:
  adapter: 0.0.0.0  # Override to use a specific adapter
  outstation-ip: 127.0.0.1
  port: 20000
protocol:
  master-address: 1
  outstation-address: 10
  unsol-class-1: false
  unsol-class-2: false
  unsol-class-3: false
polls: []
profiles:
  - name: BreakerEventProfile
    poll-name: unsolicited
    mapping:  # profile model starts here
      eventMessageInfo:
        messageInfo:
          identifiedObject:
            description:
              value:
                string-field-type: ignored
            mRID:
              value:
                string-field-type: generated_uuid
            name:
              value:
                string-field-type: ignored
          messageTimeStamp:
            timestamp-field-type: message
      breaker:
        conductingEquipment:
          namedObject:
            description:
              value:
                string-field-type: ignored
            name:
              value:
                string-field-type: ignored
          mRID:
            string-field-type: primary_uuid
            value: "d4f19a3f-c6f2-4c4d-96fc-22c63a73ffdf"
      breakerEvent:
        eventValue:
          identifiedObject:
            description:
              value:
                string-field-type: ignored
            mRID:
              value:
                string-field-type: ignored
            name:
              value:
                string-field-type: ignored
        statusAndEventXCBR:
          logicalNodeForEventAndStatus:
            logicalNode:
              identifiedObject:
                description:
                  value:
                    string-field-type: ignored
                mRID:
                  value:
                    string-field-type: ignored
                name:
                  value:
                    string-field-type: ignored
            Beh:
              q:
                quality-field-type: ignored
              stVal:
                enum-field-type: ignored
              t:
                timestamp-field-type: ignored
            EEHealth:
              d:
                value:
                  string-field-type: ignored
              stVal:
                enum-field-type: ignored
          DynamicTest:
            q:
              quality-field-type: ignored
            stVal:
              enum-field-type: mapped
              source-type: binary  # {none, binary}
              index: 0
              when-true: DynamicTestKind_none
              when-false: DynamicTestKind_testing
            t:
              timestamp-field-type: ignored
          Pos:
            q:
              quality-field-type: ignored
            stVal:
              enum-field-type: mapped
              source-type: none  # {none, binary}
              index: 0
              when-true: DbPosKind_transient
              when-false: DbPosKind_closed
            t:
              timestamp-field-type: ignored
      ied:
        identifiedObject:
          description:
            value:
              string-field-type: ignored
          mRID:
            value:
              string-field-type: ignored
          name:
            value:
              string-field-type: ignored
