# SPDX-FileCopyrightText: 2021 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

name: build-default

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - uses: cachix/cachix-action@v14
        with:
          name: oesinc      
      - name: Build default
        run: nix-build all.nix
        timeout-minutes: 180
