# SPDX-FileCopyrightText: 2021 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

---
  name: "Nix Docker Build"
  on:
    push:
      branches: ["develop"]
      tags:
        - 'v*'    
    pull_request:
      branches: ["develop"]
  jobs:
    build:
      runs-on: self-hosted
      permissions:
        contents: read
        id-token: write
      env:
        PUSH_IMAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
      steps:
        - name: Git sha
          uses: benjlevesque/short-sha@v2.1
          id: git-sha
          with:
            length: 8
        - name: Checkout code with submodules
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - uses: cachix/install-nix-action@v20
          with:
            nix_path: nixpkgs=channel:nixos-21.11
        - uses: cachix/cachix-action@v12  
          with:
            name: openfmb-adapter
            authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        - name: Build all
          run: nix-build all.nix
          timeout-minutes: 360
        - name: Ok
          run: nix-shell --run "echo OK"
        - name: cosign
          uses: sigstore/cosign-installer@main
        - name: Login to DockerHub
          if: ${{ env.PUSH_IMAGES == 'true' }}
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Prepare Artifacts and push to DockerHub
          env:
            COSIGN_EXPERIMENTAL: "1"
          if: ${{ env.PUSH_IMAGES == 'true' }}
          run: |
            mkdir artifacts            
            cp -r `readlink result-2` artifacts/.            
            cp -r `readlink result-4` artifacts/.
            cp -r `readlink result-6` artifacts/.
            cd artifacts 
            # Push Armv8 Image to DockerHub           
            echo "Push Armv8 Image to DockerHub"
            IMAGE_NAME=$(find . -name *docker*aarch64*.tar.gz)
            docker load --input $IMAGE_NAME
            IMAGE_REPOSITORY=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep aarch64)
            echo $IMAGE_REPOSITORY
            docker tag $IMAGE_REPOSITORY docker.io/oesinc/openfmb.adapters:aarch64-${{ steps.git-sha.outputs.sha }}
            docker push docker.io/oesinc/openfmb.adapters:aarch64-${{ steps.git-sha.outputs.sha }}
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_REPOSITORY)            
            echo "Sign Image with Cosign for: $IMAGE_DIGEST"
            cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" $IMAGE_DIGEST
            # Push Armv7 Image to DockerHub
            echo "Push Armv7 Image to DockerHub"
            IMAGE_NAME=$(find . -name *docker*armv7*.tar.gz)
            docker load --input $IMAGE_NAME
            IMAGE_REPOSITORY=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep armv7)
            echo $IMAGE_REPOSITORY
            docker tag $IMAGE_REPOSITORY docker.io/oesinc/openfmb.adapters:armv7-${{ steps.git-sha.outputs.sha }}
            docker push docker.io/oesinc/openfmb.adapters:armv7-${{ steps.git-sha.outputs.sha }}
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_REPOSITORY)            
            echo "Sign Image with Cosign for: $IMAGE_DIGEST"
            cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" $IMAGE_DIGEST           
            # Push x86_64 Image to DockerHub
            echo "Push x86_64 Image to DockerHub"
            IMAGE_NAME=$(find . -name *docker*x86_64*.tar.gz)
            docker load --input $IMAGE_NAME
            IMAGE_REPOSITORY=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep x86_64)
            echo $IMAGE_REPOSITORY
            docker tag $IMAGE_REPOSITORY docker.io/oesinc/openfmb.adapters:x86_64-${{ steps.git-sha.outputs.sha }}
            docker push docker.io/oesinc/openfmb.adapters:x86_64-${{ steps.git-sha.outputs.sha }}
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_REPOSITORY)            
            echo "Sign Image with Cosign for: $IMAGE_DIGEST"
            cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" $IMAGE_DIGEST 
            # Create and push the multiarch Image to DockerHub
            echo "Create and push the multiarch Image to DockerHub"
            IMAGE_NAME=${GITHUB_REPOSITORY#*/}            
            docker manifest create \
              oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} \
              --amend oesinc/$IMAGE_NAME:x86_64-${{ steps.git-sha.outputs.sha }} \
              --amend oesinc/$IMAGE_NAME:armv7-${{ steps.git-sha.outputs.sha }} \
              --amend oesinc/$IMAGE_NAME:aarch64-${{ steps.git-sha.outputs.sha }}
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:x86_64-${{ steps.git-sha.outputs.sha }} --arch amd64 --os linux
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:armv7-${{ steps.git-sha.outputs.sha }} --arch arm --os linux --variant v7
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:aarch64-${{ steps.git-sha.outputs.sha }} --arch arm64 --os linux            
            docker manifest push oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }}
            docker manifest create \
              oesinc/$IMAGE_NAME:latest \
              --amend oesinc/$IMAGE_NAME:x86_64-${{ steps.git-sha.outputs.sha }} \
              --amend oesinc/$IMAGE_NAME:armv7-${{ steps.git-sha.outputs.sha }} \
              --amend oesinc/$IMAGE_NAME:aarch64-${{ steps.git-sha.outputs.sha }}
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:x86_64-${{ steps.git-sha.outputs.sha }} --arch amd64 --os linux
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:armv7-${{ steps.git-sha.outputs.sha }} --arch arm --os linux --variant v7
            docker manifest annotate oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }} oesinc/$IMAGE_NAME:aarch64-${{ steps.git-sha.outputs.sha }} --arch arm64 --os linux            
            docker manifest push oesinc/$IMAGE_NAME:latest
            # Sign the multiarch Image with Cosign
            IMAGE_URL=oesinc/$IMAGE_NAME:${{ steps.git-sha.outputs.sha }}
            docker pull $IMAGE_URL
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_URL)            
            echo "Sign Image with Cosign for: $IMAGE_DIGEST"
            cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" $IMAGE_DIGEST
