# SPDX-FileCopyrightText: 2021 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

---
  name: "Nix Build"
  on:
    push:
  jobs:
    build:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v3
        - uses: cachix/install-nix-action@v20
          with:
            nix_path: nixpkgs=channel:nixos-21.11
        - uses: cachix/cachix-action@v12
          with:
            name: openenergysolutions            
        - name: Update submodules          
          run: git submodule update --init
        - name: Build all          
          run: nix-build default.nix
        - name: Ok
          run: nix-shell --run "echo OK"
 
          