# SPDX-FileCopyrightText: 2021 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Nix Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_IMAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
      - uses: cachix/cachix-action@v10

        with:
          name: openenergysolutions
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Update submodules
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git submodule update --init
      - name: Build all
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: nix-build default.nix
      - name: Ok
        run: nix-shell --run "echo OK"
