# SPDX-FileCopyrightText: 2021 Open Energy Solutions Inc
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Nix Build"
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PUSH_IMAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - uses: cachix/cachix-action@v12
        with:
          name: oesinc
          # authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Update submodules
        # env:
        #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git submodule update --init
      - name: Build all
        # env:
        #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: nix-build default.nix
      - name: Ok
        run: nix-shell --run "echo OK"
